platform :ios, '9.0'
use_frameworks!

target 'Weibo' do
    pod 'AFNetworking', '~> 3.2.1'
    pod 'YYModel', '~> 1.0.4'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'pop', '~> 1.0.9'
    pod 'SnapKit', '~> 4.2.0'
    
end
